version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - 6380:6379
    volumes:
    - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning
    restart: unless-stopped
    
volumes:
  redis-data: {}